const ASYNC_KEY = {
  FCM_TOKEN: 'FCM_TOKEN',
};

const CONSTANTS = {
  NAVIGATION_PARAM_HEADER_HAS_DATA_STYLE:
    'NAVIGATION_PARAM_HEADER_HAS_DATA_STYLE',
  NAVIGATION_PARAM_HEADER_LOADING_STYLE:
    'NAVIGATION_PARAM_HEADER_LOADING_STYLE',
  NAVIGATION_PARAM_HEADER_ERROR_STYLE: 'NAVIGATION_PARAM_HEADER_ERROR_STYLE',
  NAVIGATION_PARAM_ID: 'NAVIGATION_PARAM_ID',
  USER_LOCATION: 'USER_LOCATION',
  TITLE: 'HEADER_TITLE',
  DATA: 'DATA',
  TYPE: 'TYPE',
  FUNCTION: 'ON_PRESSED_FUNCTION',
  PARAMS: 'PARAMS',
  ADDITIONAL_PARAMS: 'ADDITIONAL_PARAMS',
  NAVIGATION_PARAM_URI: 'URI',
};

const ROUTE_NAMES = {
  CONTACT: 'CONTACT',
  CONTACT_FORM: 'CONTACT_FORM',
  SCREEN_INPUT: 'SCREEN_INPUT',
  ONBOARDING_INTRO: 'ONBOARDING_INTRO',
  LOGIN: 'LOGIN',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  FORGOT_PASSWORD_PHONE: 'FORGOT_PASSWORD_PHONE',
  FORGOT_PASSWORD_FORM: 'FORGOT_PASSWORD_FORM',
  ACCOUNT: 'ACCOUNT',
  HOME: 'HOME',
};

export {CONSTANTS, ROUTE_NAMES, ASYNC_KEY};
